### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by TomlandHilarious** [A17138501/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [] All screenshots correspond to the described steps
- [] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

Missing screenshots for certain commands, such as scp and logging onto the remote server without a password. 
Some titles of sections are wrong and are not formatted correctly using markdown.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by A17138501** [comment]
I fixed the part of that logging to onto remote server without password and also change and add the last part with a title Optimizing Remote Running and a new change screenshot to describe what i did in that part.

**Comment by TomlandHilarious** [comment]
Hi, the screenshots are now correct. However, the titles are not fixed yet (should be in markdown header)

**Comment by A17138501** [comment]
I have added markdown in it, it should work correctly this time
